### ISSUE TITLE
loading server resource pack destroys font

### ISSUE THREAD

**Issue by deltanedas** [alphaqu/DashLoader-Legacy#1]
after joining a server and loading its provided resource pack, every font glyph is a square.
![Screenshot_22:33:37](https://user-images.githubusercontent.com/39013340/114100140-c4068500-98bb-11eb-9595-2b3b9a1ff02d.png)

only related thing in logs was
```
[Worker-Main-1/INFO]: [STDOUT]: loaded splash fast
[Worker-Main-1/INFO]: [STDOUT]: Preparing fonts.
[Worker-Main-1/INFO]: [STDOUT]: minecraft:font/glyph_sizes.bin
[Worker-Main-1/INFO]: [STDOUT]: minecraft:font/glyph_sizes.bin
```

full log:
[latest.log](https://github.com/alphaqu/DashLoader/files/6281724/latest.log)

----

additionally as per the screenshot, custom models and textures do not work at all.

**Comment by alphaqu** [comment]
The logs there dont help at all as its expected. the recaching has not been implemented so after first launch if you change the resource pack nothing will change. Wait until full release and it will be fixed.

**Comment by deltanedas** [comment]
ok
