### ISSUE TITLE
Dashloader stuck on "Serializing Atlas" when updating texture pack

### ISSUE THREAD

**Issue by IkeVoodoo** [alphaqu/DashLoader-Legacy#12]
There is not much to it, add or remove a texture pack and after the normal minecraft loading screen is done, dashloader will kick in and get to "Serializing Atlas" and get stuck there, pressing "esc" (escape) will close the dashloader loading screen. Nothing seems off and the texture pack(s) (un)load correctly.

Screenshot:
![image](https://user-images.githubusercontent.com/55694349/116278916-3c5bba00-a787-11eb-9951-c16b7553057a.png)

**Comment by xcfrg** [comment]
Can reproduce

**Comment by Kamillaova** [comment]
same.
![image](https://user-images.githubusercontent.com/54859825/116569846-71e0de80-a912-11eb-9ba1-ff8b280d504c.png)
![image](https://user-images.githubusercontent.com/54859825/116569898-7dcca080-a912-11eb-8ed7-10ddc5cf7c5d.png)

**Comment by Kamillaova** [comment]
Hmm, fixed with 77dffe527449526122049a417b97c5988ec14649

**Comment by alphaqu** [comment]
Fixed with 1.2-alpha
