### ISSUE TITLE
16/17 serializing... 

### ISSUE THREAD

**Issue by superon** [alphaqu/DashLoader-Legacy#14]
this is where it fails for me, left it for 5 minutes and tried reloading to see it do the same thing :/
v1.0.2
i have this hopefully helpful https://pastebin.com/zzh3r9VN

**Comment by Minenash** [comment]
Can you provide the full log?

**Comment by superon** [comment]
i did try but i don't have pro pastebin...i can abridge it
https://pastebin.com/DaPLxshh
abridged with ellipsis

**Comment by superon** [comment]
that is latest.log

**Comment by Minenash** [comment]
try without adorn

**Comment by superon** [comment]
oh.. that made it fail quicker, assuming it wasn't going to go anywhere from here i killed it
https://pastebin.com/s08GTBfc

**Comment by Minenash** [comment]
If you didn't already, can you try manually clearing the cache and trying again. It's mostly likely incompatible with (at least) one of the mods you have. For the first log, you said you couldn't post the whole thing, so I don't know if there were any unsupported models warnings in them

**Comment by superon** [comment]
most of what was left out in the "first" log was lines pretty similar to those above and below them, nothing particularly particular looking about them

**Comment by superon** [comment]
guessing 15 models failed are the 15 lines preceding line 406

**Comment by Minenash** [comment]
Oh I missed that. Try removing that mod

**Comment by superon** [comment]
that's 6 mods that are integral, it won't load without them anyway... is it a case that dashLoader 100% doesn't work with any mods using baked models?

**Comment by Minenash** [comment]
Custom models in general (or at least the ones with it's own class)

**Comment by superon** [comment]
ok, so long it that's what is causing this i will suggest updating the description to properly reflect this behaviour
