### ISSUE TITLE
Wrong license in mod metadata

### ISSUE THREAD

**Issue by deralmas** [alphaqu/DashLoader-Legacy#15]
Hi, your mod is really great, it's unreal how fast it goes!
This isn't really a bug report, more a small nitpick if anything:
Although this project is licensed by the LGPL 2.1, its `fabric.mod.json` says otherwise, [reporting a MIT license](https://github.com/alphaqu/DashLoader/blob/77dffe527449526122049a417b97c5988ec14649/src/main/resources/fabric.mod.json#L15).

Could you fix this small incoherence? Other than that, I can't seem to find any issue for now.

**Comment by alphaqu** [comment]
Fixed.
