### ISSUE TITLE
Resource pack caching

### ISSUE THREAD

**Issue by deralmas** [alphaqu/DashLoader-Legacy#16]
Ok, remember when I said that I didn't find any problems? I spoke too soon XD

Basically, everytime there's a resource pack change, the cache gets invalidated and is reserialized. The issue with this approach is that joining and quitting a server with a custom resource pack causes the reserialization to happen every time.

Would it be possible to cache the game content by resource pack? You could probably use its SHA1, just like the game does.
This way joining and quitting a server with a custom resource pack would be way less annoying.

**Comment by alphaqu** [comment]
Added in 2.0
