### ISSUE TITLE
Resource Packs are not functioning properly

### ISSUE THREAD

**Issue by FwuffyPetsOwO** [alphaqu/DashLoader-Legacy#18]
Some things with Resource packs don't work the way they should. When you load up a resource pack in a world, the textures are not correct, but it can be fixed in-game in a number of ways. It also happens on servers.

Here's a video I made that shows the bug: https://youtu.be/5e4kegp0x6M

This is my mods list (none of them did anything to resource packs until I added DashLoader):
![mods list](https://user-images.githubusercontent.com/65428450/116829113-f53f4180-ab57-11eb-9ed3-50c88766438d.png)

Edit: I am on 2021 Macbook Pro with M1 chip. Other than this one bug, DashLoader works perfectly.

**Comment by alphaqu** [comment]
So after looking more into the video you are not actually loading from the dashCache. This is prob some leftover from it caching it and something going bad.

**Comment by Felix14-v2** [comment]
I have a similar problem: https://youtu.be/XB8LUeL7n8M
By the way, is it possible to cache resources once before exiting the game? At least as an option. Caching after each resource reload is a bit of a hindrance.

**Comment by alphaqu** [comment]
Fixed in 2.0
