### ISSUE TITLE
Missing chunks and game freeze with Sodium

### ISSUE THREAD

**Issue by Felix14-v2** [alphaqu/DashLoader-Legacy#22]
When Minecraft is launched from the cache along with sodium, it leads to rendering errors of some chunks and the game freezing after a while.
(the first launch is fine)

**To Reproduce**
• Launch Minecraft with DashLoader v1.3.1 and Sodium v0.1.0
• Open singleplayer world – all is fine
• Close Minecraft
• Launch Minecraft again to load it from the cache
• Open singleplayer world
• Get the window freezing after a while

**Logs**
[2021-05-06-7.log](https://github.com/alphaqu/DashLoader/files/6434725/2021-05-06-7.log) (First launch)
[latest.log](https://github.com/alphaqu/DashLoader/files/6434700/latest.log) (Second launch)

**Comment by pluiedev** [comment]
Sodium 0.1.0 is unsupported, please use the latest dev builds in the `1.16.x/next` branch, which should be the default

**Comment by pluiedev** [comment]
FYI: link with the recommended build via GitHub Actions, just click on "build-artifacts" below "Artifacts", unzip and find the jar without a `-dev`, `-sources` or `-sources-dev` suffix
https://github.com/CaffeineMC/sodium-fabric/suites/2519833185/artifacts/54565835

N.B. @alphaqu don't close this; we have enough sodium incompatibility reports on GH that this deserves to be remained open and pinned
Edit: ping 'cos it's important and i feel like it
Editedit: wrong suffixes smh

**Comment by alphaqu** [comment]
I added a breaks sodium <= 0.1.0 so starting from 1.4.1 any sodium below 0.1.0 will stop the game to start

**Comment by alphaqu** [comment]
We have fancy list now.
