### ISSUE TITLE
Custom Font and Enhanced Block Entities Dynamic model cannot be cached and not supported !!!

### ISSUE THREAD

**Issue by Trirez** [alphaqu/DashLoader-Legacy#23]
Log:    https://paste.ee/p/cvcjI

Mod:  https://modrinth.com/mod/ebe

Font Resource Pack: 
[glacial-indifference.zip](https://github.com/alphaqu/DashLoader/files/6459286/glacial-indifference.zip)

**Comment by alphaqu** [comment]
This incompatibility is already known, A fork of EBE has been created that supports DashLoader aldough it has not been merged yet.
