### ISSUE TITLE
Dashloader causes crashes whenever you get attacked by a husk

### ISSUE THREAD

**Issue by QPCrummer** [alphaqu/DashLoader-Legacy#24]
I have tried connecting to a server and it kicks me after I get hit by a husk

[crash-2021-05-12_16.15.52-client.txt](https://github.com/alphaqu/DashLoader/files/6468942/crash-2021-05-12_16.15.52-client.txt)

Version: 1.3.1STABLE
Other mods: FAPI 34.2

**Comment by alphaqu** [comment]
This was fixed in 1.4.2
