### ISSUE TITLE
crashing with sodium and iris

### ISSUE THREAD

**Issue by PhantomG27249** [alphaqu/DashLoader-Legacy#29]
[crash-2021-06-06_16.46.30-client.txt](https://github.com/alphaqu/DashLoader/files/6605143/crash-2021-06-06_16.46.30-client.txt)

Happens with sodium iris which is based on next branch

**Comment by alphaqu** [comment]
Send entire logs

**Comment by PhantomG27249** [comment]
[latest.log](https://github.com/alphaqu/DashLoader/files/6615134/latest.log)

Can't even get past the caching after a more recent update

**Comment by alphaqu** [comment]
Its not crashing because of iris or sodium, you are using LambdaBetterGrass and ConnectedBlockTextures Which are both unsupported
