### ISSUE TITLE
Causes issues when used with Connected Block Textures

### ISSUE THREAD

**Issue by ZtereoHYPE** [alphaqu/DashLoader-Legacy#31]
When the game loads from the dash cache and the mod Connected Block Textures is installed, it causes a lot (1.4k) of errors that say "model not found in data" to appear in the log and all models and textures seem to be missing, along with some strange rendering issues, and random crashes in some worlds.
This happens also when sodium and indium are installed along cbt, but not when sodium and indium alone are installed.

![2021-06-11_20 19 43](https://user-images.githubusercontent.com/57519662/121732886-100bbb00-caf3-11eb-8175-c622bd1521c9.png)
![2021-05-11_11 34 44](https://user-images.githubusercontent.com/57519662/121733077-4e08df00-caf3-11eb-8bbb-d409d425f0c7.png)

[latest.log](https://github.com/alphaqu/DashLoader/files/6640344/latest.log)

**Comment by alphaqu** [comment]
ConnectedBlockTextures is unsupported
