### ISSUE TITLE
Switch to LGPLv3.0 from LGPLv2.1

### ISSUE THREAD

**Issue by alphaqu** [alphaqu/DashLoader-Legacy#38]
@LeoCTH 👍
@RDKRACZ 👍
@NebelNidas 👍
@BasiqueEvangelist 👍
@Siuolthepic 👍
Are you ok with this switch?

**Comment by NebelNidas** [comment]
Yes, I prefer LGPL3 myself! 👍

**Comment by Siuolplex** [comment]
A switch to 3.0 would be perferred. I approve.

**Comment by K0-RR** [comment]
Yes, of course.

**Comment by pluiedev** [comment]
:+1:

**Comment by BasiqueEvangelist** [comment]
:+1:

**Comment by alphaqu** [comment]
Closed with commit b4caf02a636c54e6da6055afd2b3fc56e442d193
