### ISSUE TITLE
Block animations (Stonecutter, smoker ect.) are not animated when using DashLoader 2.0

### ISSUE THREAD

**Issue by VanillaSylv** [alphaqu/DashLoader-Legacy#40]
the title of the issue says it all.

How to trigger the issue i guess:
Load a world, or join a server. You can see the stonecutter being stuck on a single frame of the animation.
(do i really need to explain it, duh?)

F3+T doesn't fix the issue either (As it did in Dashloader 1.5)

**Comment by alphaqu** [comment]
It took me 5 hours of my time to realize this is a nonissue as it's sodium that is causing it. Next time please check if it's another mod issue and then open an issue.
