### ISSUE TITLE
PSA: DashLoader is incompatible with Sodium for 1.17.1 yet.

### ISSUE THREAD

**Issue by K0-RR** [alphaqu/DashLoader-Legacy#41]
After adding DashLoader Minecraft launched fine but the next time I tried to start the game it crashed. 
I removed a mod to force cleaning of the cache and it launched, I closed the game I tried to launch again, and got another crash.
https://paste.ee/p/RyU55

**Comment by Lyxles** [comment]
Yep had the same issue

**Comment by Lyxles** [comment]
It gets stuck on the loading screen and spams the log

**Comment by Minenash** [comment]
Does it do it for 1.17? It hadn't been officially updated for 1.17.1

**Comment by CamperSamu** [comment]
The crash is related to Sodium in 1.17.1 with DashLoader, if you disable one of the 2 mods Minecraft won't crash.

**Comment by alphaqu** [comment]
Sodium in 1.17.1 is unstable. Just dont use it with dashloader until it fully releases

**Comment by SnoFox** [comment]
In my testing, this crash appears explicitly due to Sodium.

Pick one: Sodium or Dashloader, until the bug is resolved.

For the dev, another crash-report using just Sodium and Dashloader, second launch: https://gist.github.com/SnoFox/ee433ac81f59a171a83f6cedb7972b41

**Comment by alphaqu** [comment]
try disabling shader cache in our config.   disablefeature[ "SHADER" ]

**Comment by SnoFox** [comment]
@alphaqu you're too fast - I just going to delete my comment since I only read the first couple messages. Derp.

That said, it appears disabling the shader cache did not help. 

dashloader.yaml:
```yaml
disabledFeatures: ["SHADER"]
```

... leads to the same stacktrace.

**Comment by alphaqu** [comment]
Aighty it was worth a try

**Comment by CamperSamu** [comment]
I suggest changing the issue name to `PSA: DashLoader is incompatible with Sodium 1.17.1 for now` + Mod Compat & non-issue flags, just to warn any user that this incompatibility exists for now.

**Comment by emielderckx** [comment]
Dashloader and Iris + Sodium even give people blue screens and a lot of crashes 1.17.1.

Seems like the blue screens were a sodium memory leak.

**Comment by RealRTTV** [comment]
I love it when my computer blue screens so much it makes me hate when crashes occur and definitely not like them slightly /s

**Comment by Merith-TK** [comment]
In my case there was no memory leak or crashes, just never finished loading, it had about 5% left on the loading bar and stopped there, 
https://mclo.gs/OpEyWqt

**Comment by leo60228** [comment]
Sodium 0.3.0 is now officially available for 1.17.1. I'd also note that I receive a crash, not a hang or a memory leak: https://paste.ee/p/JBgg1

**Comment by MissGamerz** [comment]
iris (1.1.1) built in sodium + sodium extras (0.3.3) + better sodium video settings with indium (1.0.0) and dash loader (2.0) and it seems fine..... this is on 1.17.1 fabricAPI (0.38.2)

**Comment by Merith-TK** [comment]
Iris has a special build of sodium, keep that in mind

**Comment by VoidNull-0** [comment]
Im using Iris and DashLoader but it doesn't crash. Instead it gets stuck at (2/12) Mapping Blockstates [0/1]. I'm also using MultiMC and 35 other mods (excluding DashLoader and Iris). The log doesn't get spammed, it doesn't move at all and if I try to quit it'll quit almost instantly as if its not busy doing anything.
<img width="966" alt="Stuckcraft" src="https://user-images.githubusercontent.com/81176903/132951692-1cfb19d3-eb0c-45e3-a03c-ee60e86cf190.png">
<img width="929" alt="Log" src="https://user-images.githubusercontent.com/81176903/132951655-a1bd94fa-bd48-4bfa-ad34-052e5c86e35e.png">

**Comment by MissGamerz** [comment]
@Merith-TK I think it's more to do with the fact that I use indium a mod that adds back the fabric renderer

**Comment by CodeF53** [comment]
I have this issue, with sodium and dashloader, I crash on second boot (cache developed)

**Comment by MissGamerz** [comment]
Just use indium as I said above..

**Comment by CodeF53** [comment]
> Just use indium as I said above..

Adding indium doesn't help.

**Comment by theRookieCoder** [comment]
Unable to replicate this with Sodium 0.3.3 and DashLoader 2.0.1
Seems this has been fixed!

**Comment by Merith-TK** [comment]
Shit even IRIS works, how i Know is that there is significant increases when I use my vanillia pack with dashloader vs without.
https://gitlab.com/Merith-TK/vanillia-modpack < my vanillia modpack
