### ISSUE TITLE
This mod conflict with optifabric1.11.1

### ISSUE THREAD

**Issue by IAFEnvoy** [alphaqu/DashLoader-Legacy#42]
Fabric loader show an error say that dash loader conflict with optifabric.

**Comment by alphaqu** [comment]
Yes because optifabric is incompatible.

**Comment by Noaaan** [comment]
Duplicate of #17, as well as a part of the pinned READ BEFORE YOU POST AN ISSUE page, #35. Please read it before opening another issue.

**Comment by Minenash** [comment]
Also for future times when fabric loader says two mods conflict, this doesn't need to be reported, as the mod author(s) had to specifically tell fabric loader that they were incomparable, so therefore it's already known
