### ISSUE TITLE
Incompatiblie with Hydrogen and FerriteCore

### ISSUE THREAD

**Issue by eshankiyer** [alphaqu/DashLoader-Legacy#43]
When launched with Hydrogen, it says error DashLoader is incompatibile with Hydrogen. When launched with FerriteCore, it launches but doesn't complete loading

**Comment by Lyxles** [comment]
Do you have sodium 1.17 Installed? Sodium 1.17 is incompatible right now.

**Comment by moehreag** [comment]
For Hydrogen, look at https://github.com/alphaqu/DashLoader/issues/35. The more interesting thing in here is FerriteCore, but I think you need to nicely ask alpha or malte (the dev/owner of FerriteCore) to add support

**Comment by K0-RR** [comment]
I'm using FerriteCore v3.0.1 with DashLoader without issues.

**Comment by Minenash** [comment]
For future reference if you make issues on other mods:
- Always check pinned issues before making one of your own.
- If fabric says mod A is incompatible with mod B, it doesn't need to be reported as mod A told fabric that
- When reporting issues (like FerriteCore not working) always include a log so the mod author have somewhere to start.

Interesting FerriteCore isn't working for you though, the last I knew it still worked. Can you provide a log?

**Comment by eshankiyer** [comment]
I do have sodium 1.17.1 BUT I removed it and Hydrogen and it still gave me a launch error. I am unable to provide a launch log right now

**Comment by Lyxles** [comment]
Hydrogen Is incompatible and Ferritecore is supported, Sodium was the problem.

**Comment by eshankiyer** [comment]
Alright.
