### ISSUE TITLE
DashLoader don't working with Enhancedblockentities

### ISSUE THREAD

**Issue by ElkRus** [alphaqu/DashLoader-Legacy#56]
I'm trying to create a super optimized build of mods in minecraft and I would like to see your mod together with Enhancedblockentities
DashLoader conflicts with Enhancedblockentities and when I try to enter the game, it crashes
Thank you for this cool mod

**Comment by K0-RR** [comment]
Duplicate of https://github.com/alphaqu/DashLoader/issues/35.

**Comment by ElkRus** [comment]
Ok thanks
