### ISSUE TITLE
Incompability

### ISSUE THREAD

**Issue by andreasdc** [alphaqu/DashLoader-Legacy#61]
Remove mod 'Connected Block Textures' (connected_block_textures) 0.1.5+1.17 (connected-block-textures-0.1.5+1.17.jar).

**Comment by alphaqu** [comment]
Yes. Do that thanks. (ps its compatible in 3.0 releases)

**Comment by andreasdc** [comment]
> Yes. Do that thanks. (ps its compatible in 3.0 releases)

3.0 release of what?

**Comment by alphaqu** [comment]
DashLoader

**Comment by andreasdc** [comment]
> DashLoader

Where to download it?

**Comment by K0-RR** [comment]
Imma join the conversation to remind that the GitHub releases page is out of date

**Comment by andreasdc** [comment]
> )

So it can't be downloaded?

**Comment by andreasdc** [comment]
> Yes. Do that thanks. (ps its compatible in 3.0 releases)

This error is on dashloader-def-3.0-beta3

**Comment by andreasdc** [comment]
@alphaqu @RDKRACZ it's not compatible

**Comment by alphaqu** [comment]
It is. I did however forget to remove the tag. Il fix this issue tommorow

**Comment by andreasdc** [comment]
> It is. I did however forget to remove the tag. Il fix this issue tommorow

I just checked with 3.0 beta4, not working.

**Comment by andreasdc** [comment]
@alphaqu any news?
