### ISSUE TITLE
Having Both Dash And Optifabric installed causes Minecraft to "Bootloop"

### ISSUE THREAD

**Issue by Blobanium** [alphaqu/DashLoader-Legacy#7]
Video of how to reproduce: https://streamable.com/ow5tch

mods folder:
![Capture](https://user-images.githubusercontent.com/45613796/115441604-e656a780-a1c5-11eb-8d95-403e9451a5cb.PNG)

And the latest.log: 
[latest.log](https://github.com/alphaqu/DashLoader/files/6345684/latest.log)

Tell me if i need anything else thanks

**Comment by alphaqu** [comment]
Hi this is a non issue as optifine likes to break compatibility with basicley every single mod, Optifabric is unsupported and i recommend you instead check out Sodium or Canvas.
