### ISSUE TITLE
Unsupported models

### ISSUE THREAD

**Issue by UltraBlackLinux** [alphaqu/DashLoader-Legacy#9]
Hey there,
New thing:
```
[09:32:04] [Thread-155/WARN]: me.lambdaurora.lambdabettergrass.model.LBGLayerBakedModel is not a supported model format, please contact mod developer to add support.
```
This has been spammed into my logs like 500 times - and I am pretty sure it's caused by your mod (As it starts with "Mapping Models") - could you maybe print this out only once?
Thanks!

**Comment by alphaqu** [comment]
Thank you for your suggestion! The log print is caused by a mod using a custom baked model and therefore will show the purple/black block on blocks that use them.
